### ISSUE TITLE
Initialize Simulation button causing AttributeError: 'Random' object has no attribute 'sample'

### ISSUE THREAD

**Issue by ibexel** [nupic-community/nupic.studio#34]
I'm fairly inexperienced with python, so i'm not 100% sure what i'm doing is right.

But I keep getting this error when i click on the 'Initialize Simulation' button. I attempted to see what was going on in the code, but i couldn't see how that method would not exist. Also went back to a git commit from Nov 1 just to see if it was because of some changes in the nupic code that might have broken this for nupic_studio. But still got the same error.

Or am i just missing something?

I'm on OSX.

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nupic_studio/ui/main_form.py", line 465, in __buttonInitHTM_Click
    initialized = Global.project.network.initialize()
  File "/Library/Python/2.7/site-packages/nupic_studio/htm/network.py", line 54, in initialize
    initialized = node.initialize()
  File "/Library/Python/2.7/site-packages/nupic_studio/htm/node_region.py", line 229, in initialize
    spVerbosity = False)
  File "/Library/Python/2.7/site-packages/nupic/research/spatial_pooler.py", line 350, in __init__
    potential = self._mapPotential(columnIndex, wrapAround=self._wrapAround)
  File "/Library/Python/2.7/site-packages/nupic/research/spatial_pooler.py", line 1265, in _mapPotential
    self._random.sample(indices, selectedIndices)
AttributeError: 'Random' object has no attribute 'sample'

**Comment by ibexel** [comment]
I ended up getting it working. I think it was because I had these two lines in my .bash_profile:

export NTA=$NUPIC/build/release
export PYTHONPATH=$PYTHONPATH:$NTA/lib/python2.7/site-packages

From memory that was what you needed back when i last set up nupic in 2013
